##each new term in the fibonacci sequence is generated by adding the previous two terms.abs
##By starting with 1 and 2, the first 10 terms will be:
## 1,2,3,5,8,13,21,34,55,89,...abs
##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

def fibonacci (num1, num2):
    result_list= [num1, num2]
    first_num = num1
    next_num = num2
    while next_num < 4000000:
        total_num = first_num + next_num
        result_list.append(total_num)
        first_num = next_num
        next_num = total_num
    return result_list

def sum_even(list_items):
    result = 0
    for item in list_items:
        if item % 2 == 0:
            result += item
    return result        

print (fibonacci (1 , 2))

print(sum_even (fibonacci (1 , 2)))